services:
  app:
    container_name: Laravel
    build: .
    volumes:
      - "../.:/var/www/html"
    ports:
      - "1606:8000"
    depends_on:
      - "db"
  db:
    image: docker.io/library/mysql:8.0
    container_name: mysql
    ports:
      - "1607:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: "Infernum"
