name: Deploy to AWS CodeDeploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: AWS Credentials
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Clean AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=$(echo '${{ secrets.AWS_ACCESS_KEY_ID }}' | tr -d '\n\r')" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo '${{ secrets.AWS_SECRET_ACCESS_KEY }}' | tr -d '\n\r')" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo '${{ secrets.AWS_SESSION_TOKEN }}' | tr -d '\n\r')" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Check identity
        run: aws sts get-caller-identity

      - name: Zip source code
        run: |
          zip -r code-deploy-app.zip . \
            --exclude="*.git*" \
            --exclude="docker-compose.yml" \
            --exclude="storage/*.gitignore"

      - name: Upload to S3
        run: |
          aws s3 cp code-deploy-app.zip s3://${{ vars.BUCKET }}/$GITHUB_SHA.zip

      - name: Create CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name backend-app \
            --deployment-group-name backend-group \
            --s3-location bucket="${{ vars.BUCKET }}",key="$GITHUB_SHA.zip",bundleType="zip"

